// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nybmmlxdetjmcvdeyvlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55Ym1tbHhkZXRqbWN2ZGV5dmxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzNDU3NDEsImV4cCI6MjA4NTkyMTc0MX0.FSzxf0aLQhs65iMtLHs0Nh6C0Rq7ti44sT-CIN8HPu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});